### PR TITLE
Fix `no-identical-title` for dynamic template strings

### LINKED ISSUE #43: no-identical-title and template strings
I'm just tying out a test like this:

```js
;[
  ['BIT_STRING', BIT_STRING],
  ['CHARACTER_STRING', CHARACTER_STRING],
  ['OCTET_STRING', OCTET_STRING]
].forEach(([title, type]) => {
  test(`decodes ${title}`, t => {
    const expected = new Buffer('foo')
    t.same(decode(type, 3, expected, 0), expected)
  })
})

;[
  ['ENUMERATED', ENUMERATED],
  ['INTEGER', INTEGER]
].forEach(([title, type]) => {
  test(`decodes ${title}`, t => {
    t.is(decode(type, 1, new Buffer([42]), 0), 42)
    const expected = new Buffer(7)
    t.same(decode(type, 7, expected, 0), expected)
  })
})
```

The `no-identical-title` complains about a duplicate title in `decodes ${title}`. It should probably recognize the title is a template string and is most likely not a duplicate.

### PR DESCRIPTION
**Pull request by jfmengels**
Fixes #43.
The `no-indentical-rule` now tries to determine whether the title is dynamic (= contains a variable) or not, so that it doesn't flag titles like `\ ̀ ensure x=${expected} \ ̀`, but still flags titles like `\ ̀ ensure x=2 \ ̀` or `\ ̀ ensure x=${1 + 3}\ ̀` (template strings without any variables). Did the same thing for titles like "foo" + 1.
I feel like I'm forgetting cases, but it should fix #43 at least.

Note: also simplified the tests to use `t => {}` rather than `function() {}`

### CODE REVIEW

**Comment by novemberborn** [comment]
Nice, thanks!

> Note: also simplified the tests to use t => {} rather than function() {}

For next time, it'd be better to do that in its own commit. Right now it makes it harder to see the actual changes.

**Comment by jfmengels** [comment]
@novemberborn you're right, my bad. If anyone wants it, I can go back and revert those changes and do a pass afterwards.

File: rules/no-identical-title.js [hunk 1]
```diff
@@ -7,6 +7,19 @@ function purify(node) {
 	return node && espurify(node);
 }
 
+function isStaticTemplateLiteral(node) {
+	return node.expressions.reduce(function (res, expr) {
+		return res && isStatic(expr);
+	}, true);
```
Comment (twada) [inline rules/no-identical-title.js]:
```js
return node.expressions.every(isStatic);
```
would be better.

Comment (jfmengels) [inline rules/no-identical-title.js]: Man, didn't even know `every` and `some` were built-in array methods. You learn everyday.

**Comment by sindresorhus** [comment]
Thanks for fixing @jfmengels :+1: 🎉

**Comment by jfmengels** [comment]
No problem :)
